Controllers/AuthenticationController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TallySoftware.Entity;
using System.Web;
using TallySoftware.Services;
using Azure;
using Microsoft.AspNetCore.Http;
using System.Net.Http;
using Newtonsoft.Json;
using System;

namespace TallySoftware.Controllers
{
    
    public class AuthenticationController : Controller
    {
        private readonly IStaffService _staffService;
        private readonly ApplicationDbContext _context;
       public AuthenticationController(ApplicationDbContext context, IStaffService staffService) { 
            _context = context;
            _staffService = staffService;
        }
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Login()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Login(Staff staff) { 
            try
            {
                if (!string.IsNullOrWhiteSpace(staff.StaffName) && !string.IsNullOrWhiteSpace(staff.Password) )
                {
                    Staff user = _staffService.GetStaff(staff.StaffName, staff.Password).Result;
                    if (user == null)
                    {
                        ViewBag.Error = "Staff not found";
                    }
                    else
                    {
                        HttpContext.Session.SetString("LoggedInUserName", user.StaffName[0]
                            .ToString().ToUpper() + user.StaffName.Substring(1,user.StaffName.Length-1));
                        HttpContext.Session.SetString("LoggedInUserType",user.StaffType);
                        
                        
                        if (user.StaffType == "Admin")
                        {
                            return RedirectToAction("dashboard", "Staff");
                        }
                        else
                        {
                            return RedirectToAction("dashboard", "Staff");
                        }
                       
                    }
                }
                else
                {
                    ViewBag.Error = "Staff not found";
                }
            }
            catch(Exception ex)
            {
                ViewBag.Error=ex.Message;
            } 
         
            return View();
        }
        [HttpGet]
        public ActionResult Logout()
        {
            //Session["loggedInUser"] = null;


            HttpContext.Session.Clear();
            return View("login");
        }

        //protected Staff GetuserByName(string username)
        //{
        //    if (!string.IsNullOrWhiteSpace(username))
        //    {
        //        return context.Staffs.FirstOrDefault(u => u.StaffName.Equals(username));
        //    }
        //    return null;
        //}
        //protected bool CheckPassword(UserEntity user, string password)
        //{
        //    return password.Equals(user.Password);
        //}


    }
}

Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TallySoftware.DTO;
using TallySoftware.Entity;
using TallySoftware.Services;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;
namespace TallySoftware.Controllers
{
    public class CustomerController : Controller
    {
        private string? customertype = null;
        private string? search = null;

        private readonly ApplicationDbContext _context;
        public CustomerController(ApplicationDbContext context)
        {
            _context = context;

        }

        [HttpGet]
        public ActionResult AddCustomer()
        {
            List<string> CustomerTypeNames = new List<string>();
            CustomerTypeNames = GetCustomerTypeName().Result;
            if (CustomerTypeNames.Count > 0)
            {
                ViewBag.customerType = CustomerTypeNames;
            }

            return View();
        }
        [HttpPost]
        public async Task<ActionResult> AddCustomer(CustomerDTO customerDTO)
        {
            if (customerDTO == null)
            {
                ViewBag.Error = "Invalid Data";
            }
            else
            {
                if (!ModelState.IsValid)
                {
                    ViewBag.Error = "Please enter the required fields";
                }
                else
                {
                    
                    Customer customer = new Customer();
                    customer = MapEntity(customer, customerDTO);
                    await _context.AddAsync(customer);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("DisplayCustomer");
                    //if (HttpContext.Session.GetString("LoggedInUserType") != null)
                    //{
                    //    String UserType = HttpContext.Session.GetString("LoggedInUserType");
                    //    if (UserType == "Admin")
                    //    {
                    //        return RedirectToAction("Admindashboard", "staff");
                    //    }
                    //    else
                    //    {
                    //        return RedirectToAction("staffdashboard", "staff");
                    //    }
                    //}
                }
            }
            return RedirectToAction("AddCustomer");
        }
        [HttpGet]
        public async Task<ActionResult> DisplayCustomer(string customertype = null, string search = null,int pageno=1)
        {
            ViewBag.usertype = HttpContext.Session.GetString("LoggedInUserType");
            this.customertype = customertype;
            this.search = search;
            ViewBag.customertype = customertype;
            ViewBag.search=search;
            ViewBag.search = !String.IsNullOrEmpty(search) ? search : null;
            var query = _context.Customers.Where(c => !c.IsDeleted).AsQueryable();
            List<string> customertypeName = new List<string>();
            customertypeName = GetCustomerTypeName().Result;
            if (customertypeName.Count > 0)
            {
                ViewBag.customertypeName = customertypeName;
            }
            if (!string.IsNullOrWhiteSpace(customertype) && customertype != "All")
            {
                query = query.Where(c => c.CustomerTypeName.Equals(customertype));
            }
            if (!string.IsNullOrWhiteSpace(search))
            {
                query = query.Where(c => c.Name.Contains(search) || c.PhoneNumber.Contains(search));
            }
            List<Customer> Customer = await _context.Customers.Where(c => !c.IsDeleted).ToListAsync();
            Customer = query.ToList();
            ViewBag.TotalCount = Customer.Count;
            int noofrecordperpage = 5;
            int noofpage = Convert.ToInt32(Math.Ceiling(Convert.ToDouble(Customer.Count) / Convert.ToDouble(noofrecordperpage)));
            int noofrecordstoskip = (pageno - 1) * noofrecordperpage;
            ViewBag.pageno = pageno;
            ViewBag.noofpage = noofpage;
            Customer = Customer.Skip(noofrecordstoskip).Take(noofrecordperpage).ToList();

            return View(Customer);
        }

        [HttpGet]
        public ActionResult ClearFilters()
        {
            this.customertype = "All";
            this.search = null;
            return RedirectToAction("DisplayCustomer");
        }
        public async Task<List<String>> GetCustomerTypeName()
        {

            List<string> customerType = await _context.CustomerTypes.Select(s => s.CustomerTypeName).ToListAsync();
            return customerType;
        }
        public Customer MapEntity(Customer customer,CustomerDTO customerDTO)
        {
            customer.Name = customerDTO.Name;
            customer.Address = !string.IsNullOrEmpty(customerDTO.Address) ? customerDTO.Address : null;
            customer.PhoneNumber = !string.IsNullOrEmpty(customerDTO.PhoneNumber) ? customerDTO.PhoneNumber : null;
            customer.AdministrativeId = customerDTO.AdministrativeId != null ? customerDTO.AdministrativeId : null;
            customer.Remark = !string.IsNullOrEmpty(customerDTO.Remark) ? customerDTO.Remark : null;
            customer.CompanyName = !string.IsNullOrEmpty(customerDTO.CompanyName) ? customerDTO.CompanyName : null;
            customer.ContactPersonName = !string.IsNullOrEmpty(customerDTO.ContactPersonName) ? customerDTO.ContactPersonName : null;
            customer.CustomerTypeName = !string.IsNullOrEmpty(customerDTO.CustomerTypeName) ? customerDTO.CustomerTypeName : null;
            customer.CustomerTypeId = customerDTO.CustomerTypeId != null ? customerDTO.CustomerTypeId : null;
            return customer;
        }

        [HttpGet]
        public async Task<ActionResult> EditCustomer(int id)
        {
            List<string> CustomerTypeNames = new List<string>();
            CustomerTypeNames = GetCustomerTypeName().Result;
            if (CustomerTypeNames.Count > 0)
            {
                ViewBag.customerType = CustomerTypeNames;
            }
            CustomerDTO customerDTO = new CustomerDTO();
            Customer customer = GetCustomerById(id).Result;
            customerDTO.Customerid = customer.CustomerId;
            customerDTO.Name = customer.Name;
            customerDTO.Address=customer.Address;
            customerDTO.PhoneNumber = customer.PhoneNumber;
            customerDTO.CompanyName=customer.CompanyName;
            customerDTO.CustomerTypeName=customer.CustomerTypeName;
            customerDTO.Remark=customer.Remark;
            customerDTO.AdministrativeId = customer.AdministrativeId;
            customerDTO.ContactPersonName=customer.ContactPersonName;
            return View(customerDTO);
        }
        [HttpPost]
        public async Task<ActionResult> EditCustomer(CustomerDTO customerDTO)
        {
            if (customerDTO != null && ModelState.IsValid)
            {
                Customer customer = new Customer();
                 customer = GetCustomerById(customerDTO.Customerid).Result;
                 customer =   MapEntity(customer,customerDTO);
                customer.UpdatedBy = HttpContext.Session.GetString("LoggedInUserName");
                customer.UpdatedOn = DateTime.Now;
                _context.Update(customer);
                await _context.SaveChangesAsync();
                return RedirectToAction("DisplayCustomer");
            }
            else
            {
                ViewBag.error = "Please enter required fields";
                return View();
            }
        }
        [HttpGet]
        public async Task<ActionResult> DeleteCustomer(int id)
        {
            Customer customer = GetCustomerById(id).Result;
            customer.IsDeleted = true;
            customer.UpdatedOn = DateTime.Now;
            customer.UpdatedBy = HttpContext.Session.GetString("LoggedInUserName");
            _context.Customers.Update(customer);
            await _context.SaveChangesAsync();
            return RedirectToAction("DisplayCustomer");
        }
            public async Task<Customer> GetCustomerById(int customerId)
        {
            var customer = await _context.Customers.FirstOrDefaultAsync(e => e.CustomerId == customerId);
            return customer;
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sai Systems</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @* <link  href="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js" /> *@
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TallySoftware.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" />
    
    <style>
        .field-validation-error, .validation-summary-errors {
            color: red;
        }
        .navbar-brand{
            font-weight:bold;
            color:#ffffff;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
            <div class="container-fluid">
                <div class="navbar-brand">Sai Systems</div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="mynavbar">
                    @if (@Context.Session.GetString("LoggedInUserName") != null)
                    {
                        <ul class="navbar-nav me-auto">
                            <li class="nav-item">
                                <a class="nav-link" onclick="location.href='@Url.Action("dashboard", "Staff")'" style="cursor:pointer">Dashboard</a>
                            </li>
                            @if (@Context.Session.GetString("LoggedInUserType") == "Admin")
                            {
                                <li class="nav-item">
                                    <a class="nav-link" onclick="location.href='@Url.Action("AddStaff", "Staff")'" style="cursor:pointer">Add Staff</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" onclick="location.href='@Url.Action("displayStaff", "Staff")'" style="cursor:pointer">Staff List</a>
                                </li>
                            }
                            
                            <li class="nav-item">
                                <a class="nav-link" onclick="location.href='@Url.Action("AddCustomer", "Customer")'" style="cursor:pointer">Add Customer</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" onclick="location.href='@Url.Action("Enquiry", "Staff")'" style="cursor:pointer">Add Enquiry</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" onclick="location.href='@Url.Action("DisplayCustomer", "Customer")'" style="cursor:pointer">Customer List</a>
                            </li>
                            
                        </ul>
                    }
                      @if (@Context.Session.GetString("LoggedInUserName") != null)
                                {
                    <form class="d-flex">
                        @* <input class="form-control me-2" type="text" placeholder="Search">
                        <button class="btn btn-primary" type="button">Search</button> *@
                        
                        <ul class="navbar-nav me-auto">
                            <li class="nav-item">
                              
                                    <p class="text-light my-0 p-2">Welcome @Context.Session.GetString("LoggedInUserName")</p>

                                
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" onclick="location.href='@Url.Action("Logout", "Authentication")'" style="cursor:pointer">Logout</a>

                            </li>
                            </ul>
                        </form>
                            }
                       
                     
                </div>
            </div>
    
        </nav>
    </header>
    <div class="container mx-auto mt-3">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted text-center">
        <div class="container">
            &copy; @DateTime.Now.Year - TallySoftware - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>